config/routes.rb
Rails.application.routes.draw do
  
  get 'questionaires/new'
  get 'questionaires/create'
  namespace :users do
    get 'activates/create'
    get 'activates/edit'
    get 'activates/update'
  end
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
  scope '/', module: :public do
    root to: 'top#index'
    resources :invitations
    resource :user_profiles
    resource :phases
    resource :questions
    resource :configs
  end
  
  namespace :users do
    resource :activates
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users
  belongs_to :phase, optional: true
  def fixed?
    users.count == 2
  end
  
  def phase_present?
    phase != 'test'
  end
end

app/models/phase.rb
class Phase < ApplicationRecord
  has_many :questions
  has_many :families
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  belongs_to :phase
  has_many :answer_options
  has_one :answer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  belongs_to :family, optional: true
  has_many :answers
  
  def update_invitation_token
    update(invitation_token: SecureRandom.hex(16))
  end
  
  def update_confirmation_number
    update(confirmation_number: rand(100000..999999))
  end
  
  def create_family
    update(family: Family.create(name: 'test_family'))
  end
  
  def answered_all?
    questions_count = Question.where(phase: family.phase).count
    questions_count == answers.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :confirmed?
  
  def confirmed?
    redirect_to edit_users_activates_path if current_user && current_user.confirmed_at.nil? && controller_name != 'activates' && request.path != sign_out_path
  end
end

app/controllers/users/activates_controller.rb
class Users::ActivatesController < ApplicationController
  def create
  end

  def edit
  end

  def update
    if current_user.confirmation_number == params[:resource][:confirmation_number]
      current_user.update(confirmed_at: Time.zone.now)
      redirect_to new_user_profiles_path, notice: '認証に成功しました！'
    else
      redirect_to edit_users_activates_path, alert: '認証番号が違います。'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do
      if resource.valid?
        resource.update_invitation_token
        resource.update_confirmation_number
        resource.create_family
        ActivationMailer.send_confirm_to_user(resource).deliver
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   edit_users_activates_path
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users/activates_helper.rb
module Users::ActivatesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FamionTrainingApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice = notice
    p.alert = alert
    .inner
      .logo
        p = link_to 'famion', root_path
      = yield

app/views/users/activates/edit.html.slim
.auth
  .card
    p 6桁の認証番号を入力してください。
    = form_for :resource, url: users_activates_path, method: 'patch' do |f|
      .field
        = f.label :confirmation_number, '認証番号'
        br
        = f.text_field :confirmation_number
      .actions
        = f.submit '認証'

= render 'users/shared/links'

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if !current_user
  - if controller_name != 'sessions'
    = link_to "ログイン", new_user_session_path
    br
  - if devise_mapping.registerable? && controller_name != 'registrations'
    = link_to "会員登録", new_user_registration_path
    br
  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to "パスワードを忘れましたか？", new_user_password_path
    br
  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to "確認メールが届きませんか？", new_user_confirmation_path
    br
  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to "Didn't receive unlock instructions?", new_user_unlock_path
    br
  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
      br
- else
  = link_to 'ログアウト', sign_out_path